name: core
version: 16.04.1
summary: snapd runtime environment
description: The core runtime environment for snapd
confinement: strict
type: os
grade: stable

parts:
  hooks:
    plugin: dump
    source: hooks
    organize:
      configure: meta/hooks/configure

  livebuild:
    source: .
    plugin: make
    build-packages:
      - livecd-rootfs
