name: core
version: 16.04.1
summary: snapd runtime environment
description: The core runtime environment for snapd
confinement: strict
type: os
grade: stable

# disabled for a short time to figure out if the security profile
# generation causes havoc with the ubuntu-core -> core transition
#hooks:
#  configure:
#    plugs:
#      - core-support

parts:
  # disabled for a short time to figure out if the security profile
  # generation causes havoc with the ubuntu-core -> core transition
  #hooks:
  #  plugin: dump
  #  source: hooks
  #  organize:
  #    configure: meta/hooks/configure

  livebuild:
    source: .
    plugin: make
    build-packages:
      - livecd-rootfs
