name: ubuntu-core
version: 16.04.1
summary: snapd runtime environment
description: The core runtime environment for snapd
confinement: strict
type: os
grade: devel

parts:
  livebuild:
    source: .
    plugin: make
    build-packages:
      - livecd-rootfs
