name: core
version: 16-2
summary: snapd runtime environment
description: The core runtime environment for snapd
confinement: strict
type: os
grade: stable

plugs:
  core-support-hook:
    interface: core-support
  network-bind-hook:
    interface: network-bind

hooks:
  configure:
    plugs: [core-support-hook, network-bind-hook]

parts:
  hooks:
    plugin: dump
    source: hooks
    organize:
      configure: meta/hooks/configure

  livebuild:
    source: .
    plugin: make
    build-packages:
      - livecd-rootfs
      - shellcheck
      - gawk
